### ISSUE TITLE
feat: Lens contract storage structure and read method

### ISSUE THREAD

**Issue by ermvrs** [keep-starknet-strange/rosettanet#10]
# Issue: Feature- Lens contract storage structure and read method

## Description

Lens contract storage has to be designed to interact with Rosetta. There might be two functions, and two mappings have to be added.

1) `get_eth_address_from_sn_address(...)` : Accepts eth address, returns starknet address.
2) `get_sn_address_from_eth_address(...)` : Accepts sn address, returns eth address.

Two relevant mappings also have to be added to storage. e.g. `LegacyMap<EthAddress, ContractAddress>`. Data types can be different. We will use hashing on address registration.

## Requirements

If you don't want to use the EthAddress type, you can use any type that can store 160 bits for the eth address type.

## Completion Time

The issue is assumed to be completed in 5 days. If you need more time, please also specify that.

**Comment by ametel01** [comment]
happy to take this

**Comment by ermvrs** [comment]
Assigned 🚀

**Comment by ermvrs** [comment]
Completed https://github.com/keep-starknet-strange/rosettanet/pull/12
