### ISSUE TITLE
feat: Lens contract address registration

### ISSUE THREAD

**Issue by ermvrs** [keep-starknet-strange/rosettanet#11]
# Issue: Feature- Lens contract write function

## Description

Lens contract storage has to be designed to interact with Rosetta. Address registration has to be permissionless and has to be checked for collisions (possibility is very low but theoretically possible). 

Convert sn address in felt range to 160-bit eth address equivalent and write to storage.

## Requirements

Tests have to be implemented correctly.

## Completion Time

The issue is assumed to be completed in 5 days. If you need more time, please also specify that.

**Comment by ermvrs** [comment]
Ill self assign this to complete asap to not block rpc part.

**Comment by Akashneelesh** [comment]
This issue can be closed.

**Comment by ermvrs** [comment]
https://github.com/keep-starknet-strange/rosettanet/pull/14 Completed
