### ISSUE TITLE
tests: Improve test `U256toUint256` tests

### ISSUE THREAD

**Issue by ermvrs** [keep-starknet-strange/rosettanet#122]
Improve tests for `src/utils/converters/integer.ts` function `U256toUint256`

Tests must be written in `tests/utils/converters/integer.test.ts`

**Comment by princeibs** [comment]
Can I hop on this?

**Comment by ermvrs** [comment]
assigned

**Comment by ermvrs** [comment]
Any updates on this issue @princeibs ?

**Comment by YakupAltay** [comment]
Hey @ermvrs! 👋
If there are no updates on @princeibs' side, I can grab this issue.

**Comment by ermvrs** [comment]
Hello @YakupAltay, assigned 👍 Please complete as soon as you can :)

**Comment by ermvrs** [comment]
Merged
https://github.com/keep-starknet-strange/rosettanet/pull/127
