### ISSUE TITLE
Wrong implementation of eth_getTransactionCount

### ISSUE THREAD

**Issue by Boreas09** [keep-starknet-strange/rosettanet#123]
In eth_getTransactionCount we get transaction count of an Address. In our middleware we are getting transaction count of a block. 

We need to implement eth_getTransactionCount with starknet_getNonce since both of them gives nonce/number of transactions of an address.

**Comment by jrmncos** [comment]
hey! I would like to take this one

**Comment by Boreas09** [comment]
Hey @jrmncos i have done it in pr #124
