### ISSUE TITLE
feat: Starknet RPC getter with fallback

### ISSUE THREAD

**Issue by ermvrs** [keep-starknet-strange/rosettanet#16]
## Description

We will need to make calls to starknet rpc. In case RPC won't respond, we should call fallback rpcs. Maybe middleware before rpc calls can also be added, but in this issue, we just need a file under the utils folder, which has a function that returns random rpc address from the list. The list can be constant in the same file.

## Requirements

The function has to be unit-tested under the tests folder. 

## Completion Time

The issue is assumed to be completed in 5 days. If you need more time, please also specify that.

**Comment by Boreas09** [comment]
Hey, can i get it?

**Comment by ermvrs** [comment]
assigned

**Comment by ermvrs** [comment]
Completed https://github.com/keep-starknet-strange/rosettanet/pull/17

**Comment by ermvrs** [comment]
https://github.com/all-contributors please add @Boreas09 for code,tests

**Comment by ermvrs** [comment]
@all-contributors please add @Boreas09 for code,tests

**Comment by ermvrs** [comment]
@all-contributors please add @Boreas09 for code,tests
