### ISSUE TITLE
feat: Implement `eth_gasPrice` method

### ISSUE THREAD

**Issue by ermvrs** [keep-starknet-strange/rosettanet#23]
## Description

We can return a constant value. There is no such method to get that from starknet rpc. however starknet fee is calculated differently.

## Requirements

- Unit tests have to be implemented. 
- Do not change the existing type structure

## Completion Time

The issue is assumed to be completed in 5 days. If you need more time, please also specify that.

**Comment by Boreas09** [comment]
hey, can i get it?

**Comment by ermvrs** [comment]
Assigned

**Comment by ermvrs** [comment]
Completed https://github.com/keep-starknet-strange/rosettanet/pull/51
