### ISSUE TITLE
feat: Implement `eth_getStorageAt` method

### ISSUE THREAD

**Issue by ermvrs** [keep-starknet-strange/rosettanet#25]
## Description

Read storage point from starknet rpc. Then return the response. Response type has to be padded to achieve same output as ethereums.

RPC Outputs
https://github.com/keep-starknet-strange/rosettanet/blob/main/rpc-call-examples/eth_getStorageAt.hurl
https://github.com/keep-starknet-strange/rosettanet/blob/main/rpc-call-examples/starknet_getStorageAt.hurl

## Requirements

- Unit tests have to be implemented. 
- Do not change the existing type structure

## Completion Time

The issue is assumed to be completed in 5 days. If you need more time, please also specify that.

**Comment by TropicalDog17** [comment]
Hi, can I work on this issue?

**Comment by ermvrs** [comment]
Assigned

**Comment by ermvrs** [comment]
@all-contributors please add @TropicalDog17 for code,tests
