### ISSUE TITLE
feat: Address validations

### ISSUE THREAD

**Issue by ermvrs** [keep-starknet-strange/rosettanet#34]
## Description

Complete the following functions under `./src/utils/validations.ts`

```ts
export function validateEthAddress(ethAddress: string): boolean {
  // TODO
  return true
}

export function validateSnAddress(snAddress: string): boolean {
  // TODO
  return true
}

```

These parameters will come from rpc requests. You have to verify whether it is valid or not. Maybe a checksum check is also good?
## Requirements

- Unit tests have to be implemented. 
- Do not change the existing type structure

## Completion Time

The issue is assumed to be completed in 5 days. If you need more time, please also specify that.

**Comment by JimmyFate** [comment]
https://github.com/starknet-io/starknet.js/blob/8bf55bff9f6edd82b5e427e94a48deb3059ebe05/src/utils/address.ts

**Comment by berzanorg** [comment]
Could I be assigned?

**Comment by ktarun1419** [comment]
i want to work on this issue @ermvrs

**Comment by ermvrs** [comment]
@berzanorg I assigned you to other one. I am assigning @ktarun1419

**Comment by ktarun1419** [comment]
Thank you, @ermvrs! I'll begin addressing the issue immediately. Is there a designated group for discussions?

**Comment by ermvrs** [comment]
Telegram group: https://t.me/rosettanet

**Comment by ermvrs** [comment]
Completed https://github.com/keep-starknet-strange/rosettanet/pull/44

**Comment by ermvrs** [comment]
@all-contributors please add @ktarun1419 for code, tests
