### ISSUE TITLE
feat: Implement `eth_getTransactionReceipt` method

### ISSUE THREAD

**Issue by ermvrs** [keep-starknet-strange/rosettanet#37]
## Description

Inputs are the same for both starknet and eth calls
https://github.com/keep-starknet-strange/rosettanet/blob/main/rpc-call-examples/eth_getTransactionReceipt.hurl
https://github.com/keep-starknet-strange/rosettanet/blob/main/rpc-call-examples/starknet_getTransactionReceipt.hurl

Get the starknet receipt result and format it into Ethereum format.

Please discuss if non-matching properties exist.

## Requirements

- Unit tests have to be implemented. 
- Do not change the existing type structure
- Tests must have non exist transaction results as well.

## Completion Time

The issue is assumed to be completed in 5 days. If you need more time, please also specify that.

**Comment by JimmyFate** [comment]
@ermvrs what's your vision for these fields?

- cumulativeGasUsed, gasUsed - one can only get the paid fee from starknet
- logs - starknet events?
- logsBloom - hardcoded 0?
- status - it probably could also be hardcoded?

**Comment by ermvrs** [comment]
cumulativeGasUsed, gasUsed : We can use paid fee
logs - SN Events if possible
logsBloom - hardcoded 0
status - Accepted on l2, l1 etc. starknet statuses but with hex (0x1,0x2...)

**Comment by berzanorg** [comment]
I would like to be assigned to this issue.

**Comment by ermvrs** [comment]
Assigned

**Comment by berzanorg** [comment]
I'm just going to put this here for future reference.

`starknet_getTransactionReceipt` JSON RPC method can either return a transaction receipt or a pending transaction receipt.

`TransactionReceipt`: https://github.com/xJonathanLEI/starknet-rs/blob/6cadb198644cf5e942187896c2e6bb3ecc9edc6e/starknet-core/src/types/mod.rs#L262

`PendingTransactionReceipt`: https://github.com/xJonathanLEI/starknet-rs/blob/6cadb198644cf5e942187896c2e6bb3ecc9edc6e/starknet-core/src/types/mod.rs#L277

**Comment by berzanorg** [comment]
Properties of the result of `starknet_getTransactionReceipt` method:
- `transaction_hash`
- `actual_fee`
- `messages_sent`
- `events`
- `execution_resources`
- `execution_result`
- `contract_address` (only DEPLOY and DEPLOY_ACCOUNT )
- `finality_status` (only non-pending)
- `block_hash` (only non-pending)
- `block_number` (only non-pending)
- `message_hash` (only L1_HANDLER)

**Comment by berzanorg** [comment]
> cumulativeGasUsed, gasUsed : We can use paid fee logs - SN Events if possible logsBloom - hardcoded 0 status - Accepted on l2, l1 etc. starknet statuses but with hex (0x1,0x2...)

If I'm not mistaken `status` property of `eth_getTransactionReceipt` method is supposed to be either `0x0` or `0x1` after the Byzantium hard fork.
I doubt that being non-compatible is okay here.
What do you think?

**Comment by ermvrs** [comment]
We don't need to support all properties, just possible ones. You can pass compatible values if there is no way to format starknet output.

**Comment by TropicalDog17** [comment]
@berzanorg maybe it's a good idea to create a (draft) PR so that is easier for @ermvrs and others to follow and give review
