### ISSUE TITLE
utils: `getContractsMethods(...)` method implementation

### ISSUE THREAD

**Issue by ermvrs** [keep-starknet-strange/rosettanet#55]
Complete the following method. It should accept the contract address (starknet) and then receive ABI from starknet rpc. Then, it returns all entry points with inputs, outputs, and function names.
```ts
export async function getContractsMethods() {
  // ...
}
```

**This issue reserved for local event in Istanbul**

Bounty: 80 **STRK**

**Comment by LucasLvy** [comment]
3h

**Comment by bilgin-kocak** [comment]
I can take this. I am coming to Istanbul event.
