### ISSUE TITLE
utils: `generateEntrypointsSelector(...)`` method implementation

### ISSUE THREAD

**Issue by ermvrs** [keep-starknet-strange/rosettanet#56]
Complete the following method. It should accept points received from getContractsMethods and then calculate the function selectors from the input. Param should be an array and returns an array.

```ts
export function generateEntrypointsSelector() {
  // ...
}
```

**This issue reserved for local event in Istanbul**

Bounty: 80 **STRK**

**Comment by LucasLvy** [comment]
2h

**Comment by melkecelioglu** [comment]
I can resolve this on Istanbul event

**Comment by berkegenckaya** [comment]
I can resolve this on Istanbul event

**Comment by ermvrs** [comment]
Still looking someone to complete this issue.

**Comment by TropicalDog17** [comment]
@ermvrs Hi, could I work on this issue?

**Comment by ermvrs** [comment]
Assigned

**Comment by melkecelioglu** [comment]
This issue assigned and resolved 29 days ago by myself. Please check the requests. It is under feature branch. @ermvrs
