### ISSUE TITLE
utils: `getContractsCustomStructs(...)` method implementation

### ISSUE THREAD

**Issue by ermvrs** [keep-starknet-strange/rosettanet#57]
Complete the following method. It should accept starknet contract address returns custom structs with native types (u256, u128 etc.)

```ts
export function getContractsCustomStructs() {
  // ...
}
```

**This issue is reserved for a local event in Istanbul**

Bounty: 160 **STRK**

**Comment by oemerfurkan** [comment]
I want to take this issue.

**Comment by princeibs** [comment]
@ermvrs Can I hop on this issue?

**Comment by ermvrs** [comment]
assigned
