### ISSUE TITLE
utils: `convertSnToEth(...)` method implementation

### ISSUE THREAD

**Issue by ermvrs** [keep-starknet-strange/rosettanet#58]
Complete the following method. 

The parameter should be starknet type as a string (u256, u128 etc). Should return eth type. Also, it should work with derived and custom types.
```ts
export async function convertSnToEth() {
  // ...
}
```

**This issue is reserved for a local event in Istanbul**

Bounty: 80 **STRK**

**Comment by ktarun1419** [comment]
I want to work on this issue @ermvrs

**Comment by LucasLvy** [comment]
2h

**Comment by alieraay** [comment]
I want to take this issue.

**Comment by ermvrs** [comment]
Still looking someone to complete this issue.

**Comment by ktarun1419** [comment]
Can you assign me @ermvrs

**Comment by ermvrs** [comment]
Assigned

**Comment by ermvrs** [comment]
Issue is available again

**Comment by muheebyusufbaba1** [comment]
I'll take this since the other one claimed to be resolved

**Comment by ermvrs** [comment]
Can you complete your current issue
https://github.com/keep-starknet-strange/rosettanet/issues/64

If that one is waiting for that tests fix. I can assign you to this one as well. But let's wait for @princeibs to complete that. Because you re going to get same error on this pr too

**Comment by muheebyusufbaba1** [comment]
Yes, we wait for him then I'll proceed

**Comment by muheebyusufbaba1** [comment]
Completed that already

**Comment by ermvrs** [comment]
Hello, i took assignation back due to inactivity.

**Comment by ermvrs** [comment]
https://github.com/keep-starknet-strange/rosettanet/pull/104 completed partially inside
