### ISSUE TITLE
dev: List of all rpc calls examples

### ISSUE THREAD

**Issue by ermvrs** [keep-starknet-strange/rosettanet#6]
# Issue: Request - Add all rpc calls inputs and outputs with example values.

## Description

This request's purpose is to make our job easier while mapping all rpc calls.

## Requirements

Create .hurl file for each rpc call. Copy inputs and outputs, for example, data for both starknet rpc and eth rpc. You can check references for the calls.

## References
https://github.com/kkrt-labs/kakarot-rpc/tree/74167501b0348ec879f3b45b485f57041e1843ce/rpc-call-examples

**Comment by Boreas09** [comment]
Hey, can i get this one?

**Comment by ermvrs** [comment]
Assigned !

**Comment by ermvrs** [comment]
Completed https://github.com/keep-starknet-strange/rosettanet/pull/13
