### ISSUE TITLE
Broken links in README

### ISSUE THREAD

**Issue by princeibs** [keep-starknet-strange/rosettanet#61]
<img width="808" alt="image" src="https://github.com/keep-starknet-strange/rosettanet/assets/64266194/3ab96a9a-c530-4ab3-bf52-362260bbf428">

Clicking on **contracts README** and **RPC README** leads to these empty pages respectively: 

<img width="1092" alt="image" src="https://github.com/keep-starknet-strange/rosettanet/assets/64266194/e8cb2d3b-0514-4974-86b4-3ef45244bcbd">

<img width="1092" alt="image" src="https://github.com/keep-starknet-strange/rosettanet/assets/64266194/21c42776-9ade-4add-b65f-f351a3877bab">

**Comment by melkecelioglu** [comment]
I can resolve this on Istanbul event

**Comment by mubarak23** [comment]
@princeibs i can solve this issue and submit a PR for it

**Comment by llinsss** [comment]
I can fix this

**Comment by ebukizy1** [comment]
i will love to work on this

**Comment by Ugo-X** [comment]
can i take this? will get it resolved in no time at all

**Comment by Ugo-X** [comment]
Can i take this? I will get resolved in no time at all
