### ISSUE TITLE
feat: Implement `eth_feeHistory` method

### ISSUE THREAD

**Issue by ermvrs** [keep-starknet-strange/rosettanet#62]
## Description

Provide similar response
https://github.com/keep-starknet-strange/rosettanet/blob/main/rpc-call-examples/eth_feeHistory.hurl

Since starknet doesn't have a fee market, simply return mock value.

## Requirements

- Unit tests have to be implemented. 
- Do not change the existing type structure

## Completion Time

The issue is assumed to be completed in 5 days. If you need more time, please also specify that.

**This issue is reserved for a local event in Istanbul**

Bounty: 80 **STRK**

**Comment by LucasLvy** [comment]
2h

**Comment by cansukaradeniz** [comment]
can i get i

**Comment by ktarun1419** [comment]
Hi @ermvrs  Can i take this issue?

**Comment by vibenedict** [comment]
Hi @ermvrs, I would like to work on this

**Comment by ermvrs** [comment]
assigned
