### ISSUE TITLE
feat: Implement `eth_getBlockByHash` method

### ISSUE THREAD

**Issue by ermvrs** [keep-starknet-strange/rosettanet#63]
## Description

Starknet's block queries are done with block hash. So simply call the related starknet method with block hash. Then, format output as same as ethereums.

https://github.com/keep-starknet-strange/rosettanet/blob/main/rpc-call-examples/eth_getBlockByHash.hurl

https://github.com/keep-starknet-strange/rosettanet/blob/main/rpc-call-examples/starknet_getBlockWithTransactions.hurl
https://github.com/keep-starknet-strange/rosettanet/blob/main/rpc-call-examples/starknet_getBlockWithTransactionHashes.hurl

Return mock values for fields that do not exist on starknet.

## Requirements

- Unit tests have to be implemented. 
- Do not change the existing type structure

## Completion Time

The issue is assumed to be completed in 5 days. If you need more time, please also specify that.

**This issue is reserved for a local event in Istanbul**

Bounty: 80 **STRK**

**Comment by AryanGodara** [comment]
@ermvrs No one seems to have picked it up in the Instanbul event.
I'm waiting for new issues to drop, so is it okay if I get on this one in the meantime? (if no one else is picking this up)

**Comment by YakupAltay** [comment]
Hey @ermvrs! 👋
I will be joining the Istanbul event on the 16th. Is it okay if I pick this issue for it?

**Comment by muheebyusufbaba1** [comment]
I'll hop on this ,thank you

**Comment by YakupAltay** [comment]
@ermvrs @muheebyusufbaba1 
I solved this issue in the İstanbul event and it is merged now: https://github.com/keep-starknet-strange/rosettanet/commit/ba6977b76be2b32a6bf8234229bcddfe2e8c2033

**Comment by ermvrs** [comment]
Oh missed that sorry.
