### ISSUE TITLE
feat: Implement `eth_getBlockByNumber` method

### ISSUE THREAD

**Issue by ermvrs** [keep-starknet-strange/rosettanet#64]
## Description

https://github.com/keep-starknet-strange/rosettanet/blob/main/rpc-call-examples/eth_getBlockByNumber.hurl

If there is a way to get block data from the block number in starknet. Get block data and format output. Otherwise, return mock values.

## Requirements

- Unit tests have to be implemented. 
- Do not change the existing type structure

## Completion Time

The issue is assumed to be completed in 5 days. If you need more time, please also specify that.

**Comment by Akashneelesh** [comment]
Hey @ermvrs , I'll take this up !!

**Comment by ermvrs** [comment]
Assigned

**Comment by Akashneelesh** [comment]
Hello @ermvrs there's already a method implemented for the same functionality (eth_blockNumber). I guess this can be closed.

**Comment by ktarun1419** [comment]
hi @ermvrs  Is this issue still relevant?

**Comment by ermvrs** [comment]
@Akashneelesh as I know you're too busy, i took this issue back from you

**Comment by muheebyusufbaba1** [comment]
Can you assign this to me? @ermvrs

**Comment by ermvrs** [comment]
assigned

**Comment by muheebyusufbaba1** [comment]
@ermvrs I started working on this already and I noticed something:
- Calling the `starknet_getBlockWithTxn` returns: 
![image](https://github.com/keep-starknet-strange/rosettanet/assets/134698940/f9e4283e-05eb-41cb-a755-a9093f871368)
- And calling `starknet_getBlockWithTxHashes` returns: 
![image](https://github.com/keep-starknet-strange/rosettanet/assets/134698940/7031b79b-88d9-4911-87dd-b9155760415c)

and those are the two methods available on Starknet to return block data. 
Comparing the response from the two rpc endpoints above, none of them seems to have enough data to return the expected object: 
![image](https://github.com/keep-starknet-strange/rosettanet/assets/134698940/221cfd91-7e22-4e76-9f02-7aa07434cba7)

Please how do you think I go about this? Or maybe there are other starknet RPC methods I am not aware of?

**Comment by ermvrs** [comment]
Please fill outputs with the values that exist on the starknet response and also if you can derive or calculate the value that fits into the response. Otherwise, if there is no chance to provide, then simply return a mock value that won't get the problem on ETH integration. Return default Ethereum values
