### ISSUE TITLE
feat: Implement `eth_getBlockTransactionCountByNumber` method

### ISSUE THREAD

**Issue by ermvrs** [keep-starknet-strange/rosettanet#66]
## Description

If there is a way to get the block hash from the block number in starknet. Then,

1) Get block hash from block number
2) Call `starknet_getBlockTransactionCount` 
3) Format response.

https://github.com/keep-starknet-strange/rosettanet/blob/main/rpc-call-examples/eth_getBlockTransactionCountByNumber.hurl
## Requirements

- Unit tests have to be implemented. 
- Do not change the existing type structure

## Completion Time

The issue is assumed to be completed in 5 days. If you need more time, please also specify that.

**Comment by TropicalDog17** [comment]
Hi, can I take this issue @ermvrs

**Comment by ermvrs** [comment]
Assigned
