### ISSUE TITLE
feat: Implement `eth_getCode` method

### ISSUE THREAD

**Issue by ermvrs** [keep-starknet-strange/rosettanet#67]
## Description

https://github.com/keep-starknet-strange/rosettanet/blob/main/rpc-call-examples/eth_getCode.hurl

1) Get sn address from queried eth address.
2) Get class hash or class opcodes for the sn address. 
3) Format output and return

## Requirements

- Unit tests have to be implemented. 
- Do not change the existing type structure
- Tests must have non-existent transaction results as well.

## Completion Time

The issue is assumed to be completed in 5 days. If you need more time, please also specify that.

**Comment by vibenedict** [comment]
Hi, I would like to be assigned to this task.

**Comment by ermvrs** [comment]
Assigned
