### ISSUE TITLE
feat: Implement `eth_getTransactionByBlockNumberAndIndex` method

### ISSUE THREAD

**Issue by ermvrs** [keep-starknet-strange/rosettanet#69]
## Description

https://github.com/keep-starknet-strange/rosettanet/blob/main/rpc-call-examples/eth_getTransactionByBlockNumberAndIndex.hurl

If possible, get block transactions from the block number on starknet—and result transaction.

## Requirements

- Unit tests have to be implemented. 
- Do not change the existing type structure
- Tests must have non-existent transaction results as well.

## Completion Time

The issue is assumed to be completed in 5 days. If you need more time, please also specify that.

**Comment by muheebyusufbaba1** [comment]
I'll like to resolve this issues I'll be glad if it assigned to me to do so!

Thank you

**Comment by ermvrs** [comment]
Assigned
