### ISSUE TITLE
feat: Implement `eth_getTransactionByHash` method

### ISSUE THREAD

**Issue by ermvrs** [keep-starknet-strange/rosettanet#70]
## Description

https://github.com/keep-starknet-strange/rosettanet/blob/main/rpc-call-examples/eth_getTransactionByHash.hurl
https://github.com/keep-starknet-strange/rosettanet/blob/main/rpc-call-examples/starknet_getTransactionByHash.hurl

A similar call exists. Just format output. Fill with mock values for non-existing properties.

## Requirements

- Unit tests have to be implemented. 
- Do not change the existing type structure
- Tests must have non-existent transaction results as well.

## Completion Time

The issue is assumed to be completed in 5 days. If you need more time, please also specify that.

**This issue is reserved for a local event in Istanbul**

Bounty: 80 **STRK**

**Comment by Boreas09** [comment]
Can i get it?

**Comment by ermvrs** [comment]
@Boreas09 I consider that you will join Istanbul event right?

**Comment by Boreas09** [comment]
Yes definitely

**Comment by ermvrs** [comment]
Completed at https://github.com/keep-starknet-strange/rosettanet/pull/87
