### ISSUE TITLE
feat: Implement `eth_getTransactionCount` method

### ISSUE THREAD

**Issue by ermvrs** [keep-starknet-strange/rosettanet#71]
## Description

https://github.com/keep-starknet-strange/rosettanet/blob/main/rpc-call-examples/eth_getTransactionCount.hurl
https://github.com/keep-starknet-strange/rosettanet/blob/main/rpc-call-examples/starknet_getBlockWithTransactions.hurl

## Requirements

- Unit tests have to be implemented. 
- Do not change the existing type structure
- Tests must have non-existent transaction results as well.

## Completion Time

The issue is assumed to be completed in 5 days. If you need more time, please also specify that.

**This issue is reserved for a local event in Istanbul**

Bounty: 40 **STRK**

**Comment by LucasLvy** [comment]
1h

**Comment by vibenedict** [comment]
May I fix this? @ermvrs

**Comment by ermvrs** [comment]
@vibenedict  assigned

**Comment by ermvrs** [comment]
@vibenedict will you be able to complete this issue?

**Comment by vibenedict** [comment]
yes
