### ISSUE TITLE
feat: Implement `eth_getTransactionReceipt` method

### ISSUE THREAD

**Issue by ermvrs** [keep-starknet-strange/rosettanet#72]
## Description

https://github.com/keep-starknet-strange/rosettanet/blob/main/rpc-call-examples/eth_getTransactionReceipt.hurl
https://github.com/keep-starknet-strange/rosettanet/blob/main/rpc-call-examples/starknet_getTransactionReceipt.hurl

Same call. Just format output.

## Requirements

- Unit tests have to be implemented. 
- Do not change the existing type structure
- Tests must have non-existent transaction results as well.

## Completion Time

The issue is assumed to be completed in 5 days. If you need more time, please also specify that.

**This issue is reserved for a local event in Istanbul**

Bounty: 80 **STRK**

**Comment by LucasLvy** [comment]
2h

**Comment by saitunc** [comment]
Hey @ermvrs 
I will attend to Istanbul event. I want to take this issue.

**Comment by Boreas09** [comment]
Hey there, can i get this?

**Comment by muheebyusufbaba1** [comment]
I'll hop on this
