### ISSUE TITLE
feat: Implement `eth_syncing` method

### ISSUE THREAD

**Issue by ermvrs** [keep-starknet-strange/rosettanet#73]
## Description

https://github.com/keep-starknet-strange/rosettanet/blob/main/rpc-call-examples/starknet_syncing.hurl
https://github.com/keep-starknet-strange/rosettanet/blob/main/rpc-call-examples/eth_syncing.hurl

Return mock values if they do not exist on the starknet response.

## Requirements

- Unit tests have to be implemented. 
- Do not change the existing type structure
- Tests must have non exist transaction results as well.

## Completion Time

The issue is assumed to be completed in 5 days. If you need more time, please also specify that.

**This issue is reserved for a local event in Istanbul**

Bounty: 40 **STRK**

**Comment by LucasLvy** [comment]
1h

**Comment by codekaya** [comment]
if it is ok i can take this one.

**Comment by codekaya** [comment]
https://github.com/keep-starknet-strange/rosettanet/pull/88

**Comment by vibenedict** [comment]
I would be my pleasure to fix this

**Comment by ermvrs** [comment]
@vibenedict do you still want to work on that issue?

**Comment by vibenedict** [comment]
Yes

**Comment by ermvrs** [comment]
I assigned you to #71

**Comment by Boreas09** [comment]
Can i do it
