### ISSUE TITLE
feat: Implement Starknet RPC functions

### ISSUE THREAD

**Issue by ermvrs** [keep-starknet-strange/rosettanet#80]
## Description

Returns starknet rpc calls directly.

## Requirements

- Unit tests have to be implemented. 
- Do not change the existing type structure
- Tests must have non exist transaction results as well.

## Completion Time

The issue is assumed to be completed in 5 days. If you need more time, please also specify that.

**This issue is reserved for a local event in Istanbul**

Bounty: 80 **STRK**

**Comment by andresmayorca** [comment]
can i work in this?

**Comment by femreka** [comment]
can i work in this

**Comment by femreka** [comment]
hi again, is it possible to give me one more day for the issue? i work on the issue but as i mentioned yesterday i am new so it takes time to understand concepts

**Comment by ermvrs** [comment]
Completed https://github.com/keep-starknet-strange/rosettanet/pull/99
