### ISSUE TITLE
test: failing test cases

### ISSUE THREAD

**Issue by princeibs** [keep-starknet-strange/rosettanet#96]
## Description
All test cases were initially passing until recently where most started failing.

## Requirement
- Investigate and fix the problem causing test cases to fail
- Update failing test cases so all can pass
- Do not change the code implementations (if possible). Only change the tests (where necessary).

**Comment by muheebyusufbaba1** [comment]
I'll like to hop on this

**Comment by ermvrs** [comment]
assigned

**Comment by princeibs** [comment]
Can I fix this?

**Comment by ermvrs** [comment]
@princeibs assigned
